name: 'Starred to Logseq'
description: 'Sync you starred repo to Logseq'
inputs:
  username:
    description: 'You can specify to use any user's data'
    default: ${{ github.repository_owner }}

  description:
    description: >
      The description for your awesome project
    default: 'A collection of awesome things.'

  repository: 
    description: >
      The owner and repository name.
    default: ${{ github.repository }}

  workflow:
    default:  ${{ github.workflow }}

  token:
    default: ${{ github.token }}
  
  targetDir:
    default: ${{ github.workspace }}

runs:
  using: 'node16'
  main: 'dist/index.js'
