name: "Starred to Logseq"
description: "Sync you starred repo to Logseq"
branding:
  icon: "star"
  color: "purple"
inputs:
  username:
    description: "You can specify to use any user data"
    default: ${{ github.repository_owner }}

  description:
    description: >
      The description for your awesome project
    default: "A collection of awesome things."

  repository:
    description: >
      The owner and repository name.
    default: ${{ github.repository }}

  token:
    description: "Specify github token if you are testing locally"
    default: ${{ github.token }}

  targetDir:
    description: "Folder generated"
    default: ${{ github.workspace }}

runs:
  using: "node20"
  main: "dist/index.js"
